apiVersion : apps/v1
kind: Deployment
metadata:
  name: "hsk8s-2b23"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "hsk8s-2b23"
  template:
    metadata:
      labels:
        app: "hsk8s-2b23"
    spec:
      containers:
        - name: "hsk8s-2b23"
          image: "hsk8stest.azurecr.io/hsk8s"
          ports:
          - containerPort: 80