apiVersion: v1
kind: Service
metadata:
    name: "hsk8s-2b23"
    labels:
        app: "hsk8s-2b23"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "hsk8s-2b23"