name: azure

on:
  schedule:
    - cron: '30 2 * * 1-5'      # Start timing is set as per UTC time zone as based on 08:00 AM IST
    - cron: '30 14 * * 1-5'     # Stop timing is set as per UTC time zone as based on 08:00 PM IST
  # workflow_dispatch:

env:
  VM_TAG_KEY: "auto"
  VM_TAG_VALUE: "yes"
  AKS_TAG_KEY: "foo"
  AKS_TAG_VALUE: "bar"  
  ResourceGroup: "RG1"

jobs:
  azureResourcesStart:
    if: github.event.schedule != '30 14 * * 1-5'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    
    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # Run commads to start the azure resources
    - name: start_azure_vm
      # if: github.event.schedule != '30 14 * * 1-5'
      run: |
       # rgstr=$(az vm list --query "[?tags.${{ env.VM_TAG_KEY }} == '${{ env.VM_TAG_VALUE }}'].{Group:resourceGroup}" -o tsv)
       # for vmrg in ${rgstr[@]}; do
       #   echo "running command with ResourceGroup $vmrg"
          vmstr=$(az vm list -g ${{ env.ResourceGroup }} --query "[?tags.${{ env.VM_TAG_KEY }} == '${{ env.VM_TAG_VALUE }}'].{Name:name}" -o tsv)
          for vm in ${vmstr[@]}; do
            echo "Starting Azure VM $vm"
            az vm start -gwefwef ${{ env.ResourceGroup }} -n $vm
          done  
       # done
        
    - name: start_azure_aks_cluster
      # if: github.event.schedule != '30 14 * * 1-5'
      run: |
       # krgstr=$(az aks list --query "[?tags.${{ env.AKS_TAG_KEY }} == '${{ env.AKS_TAG_VALUE }}'].{Group:resourceGroup}" -o tsv)
       # for krg in ${krgstr[@]}; do
       #   echo "running command with ResourceGroup $krg"
          kclusterstr=$(az aks list -g ${{ env.ResourceGroup }} --query "[?tags.${{ env.AKS_TAG_KEY }} == '${{ env.AKS_TAG_VALUE }}'].{Name:name}" -o tsv)
          for kcluster in ${kclusterstr[@]}; do
            echo "Starting Azure AKS $kcluster"
            az aks start -g ${{ env.ResourceGroup }} -n $kcluster
          done  
       # done
    
    - name: Send GitHub Action trigger data to Slack workflow
      if: always()
      # if: github.event.schedule != '30 14 * * 1-5'
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: '#azure-notifications'
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ github.job }} ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
               "type": "section",
                "text": {
                 "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ github.job }} ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


  azureResourcesStop:
    if: github.event.schedule != '30 2 * * 1-5'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:

    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
    # Run commads to stop the azure resources
    - name: stop_azure_vm
    #  if: github.event.schedule != '30 2 * * 1-5'
      run: |
       # rgstr=$(az vm list --query "[?tags.${{ env.VM_TAG_KEY }} == '${{ env.VM_TAG_VALUE }}'].{Group:resourceGroup}" -o tsv)
       # for vmrg in ${rgstr[@]}; do
       #   echo "running command with ResourceGroup $vmrg"
          vmstr=$(az vm list -g ${{ env.ResourceGroup }} --query "[?tags.${{ env.VM_TAG_KEY }} == '${{ env.VM_TAG_VALUE }}'].{Name:name}" -o tsv)
          for vm in ${vmstr[@]}; do
            echo "Stopping Azure VM $vm"
            az vm stop -g ${{ env.ResourceGroup }} -n $vm
            echo "Running deallocating command"
            az vm deallocate -g ${{ env.ResourceGroup }} -n $vm
          done  
       # done

    - name: stop_azure_aks_cluster
     # if: github.event.schedule != '30 2 * * 1-5'
      run: |
       # krgstr=$(az aks list --query "[?tags.${{ env.AKS_TAG_KEY }} == '${{ env.AKS_TAG_VALUE }}'].{Group:resourceGroup}" -o tsv)
       # for krg in ${krgstr[@]}; do
       #   echo "running command with ResourceGroup $krg"
          kclusterstr=$(az aks list -g ${{ env.ResourceGroup }} --query "[?tags.${{ env.AKS_TAG_KEY }} == '${{ env.AKS_TAG_VALUE }}'].{Name:name}" -o tsv)
          for kcluster in ${kclusterstr[@]}; do
            echo "Stopping Azure AKS $kcluster"
            az aks stop -g ${{ env.ResourceGroup }} -n $kcluster
          done  
       # done

    - name: Send GitHub Action trigger data to Slack workflow
      if: always()
      # if: github.event.schedule != '30 2 * * 1-5'
      id: slack
      uses: slackapi/slack-github-action@v1.19.0
      with:
        # Slack channel id, channel name, or user id to post message.
        # See also: https://api.slack.com/methods/chat.postMessage#channels
        channel-id: '#azure-notifications'
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ github.job }} ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
              {
               "type": "section",
                "text": {
                 "type": "mrkdwn",
                  "text": "GitHub Action build result: ${{ github.job }} ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        # SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}