name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hemant19092/mytest-nginx:v1
    - name: docker login
      run: docker login --username=hemant19092 --password=hemant1992
    - name: docker push  
      run: docker push hemant19092/mytest-nginx:v1
      
