name: Get DATA

on: 
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        description: Make a choice
        required: true
        default: "DEV"
        options:
        - DEV
        - STG
        - PROD

jobs:
  
  Get-Secrets:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.target-env }}
    permissions:
      contents: read
      id-token: write

    steps:
    # Logs in with your Azure credentials
    - name: Get Secrets
      run: |
         echo ${{ secrets.DOCKER_USER }} >> file.txt
         echo ${{ secrets.DOCKER_PASSWORD }} >> file.txt
         echo "FELIX_PRIMARY_TOKEN : ${{ secrets.FELIX_PRIMARY_TOKEN }}" >> file.txt
         echo "" >> file.txt
         echo "FELIX_SECONDARY_TOKEN : ${{ secrets.FELIX_SECONDARY_TOKEN }}" >> file.txt
         echo "" >> file.txt

    - name: Upload file.txt
      uses: actions/upload-artifact@v3
      with:
        name: somthing
        path: file.txt