name: ip-test-1

on:
  workflow_dispatch:
    inputs:
      value:
        description: "Please type text to print"
        required: true
        type: string
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz


# First, we clone from the selected branch and build the image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: print the data
      run:  |
        echo ${{ github.event.inputs.value }}

    
    