name: ip-test-1

on:
  workflow_dispatch:
    inputs:
      value:
        description: "Please provide custom tags or use the go to google.com"
        required: false
        type: string
      # choice:
      #   type: choice
      #   description: Make a choice
      #   required: false
      #   default: " "
      #   options:
      #   - ${{ env.file }}
      #   - bar
      #   - baz


env:
  file: "curl -s 'https://magdevops.blob.core.windows.net/githubactions/stgImageVersion/version.txt?sp=racwdl&st=2022-07-19T11:40:35Z&se=2023-07-19T19:40:35Z&spr=https&sv=2021-06-08&sr=c&sig=73UmLXJsUSnmh8vQ4Sn%2F5Z0v6Q%2BmntLNA%2BEW1%2F2revI%3D' | tail -1"

# First, we clone from the selected branch and build the image
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    
    steps:
    - name: print the data
      id: step1
      run:  |
        if [[ -z "${{ inputs.value }}" ]]
        then
          echo "No custom tags"
          echo "::set-output name=test::${{ inputs.choice }}"
        else
          echo "Custom tags: ${{ inputs.choice }}"
          echo "::set-output name=test::${{ inputs.value }}"
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo ${{needs.build.outputs.output1}} ${{needs.build.outputs.output2}}
    
    