name: snyk-test

on: 
  workflow_dispatch:
    inputs:
      image:
        description: "Please provide container image name"
        required: true
        type: string

jobs:
  Login_docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  Security_test:
    runs-on: ubuntu-latest
    needs: Login_docker
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ inputs.image }}