name: auto start azure resources

on:
  schedule:
    - cron: '05 03 * * 0'
  workflow_dispatch:

env:
  VM_TAG_KEY: "auto"
  VM_TAG_VLAUE: "yes"
  AKS_TAG_KEY: "foo"
  AKS_TAG_VLAUE: "bar"

jobs:
  azureResourcesStart:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    # Checks out the repository this file is in
    #- uses: actions/checkout@v3
    
    # Logs in with your Azure credentials
    - name: Azure login
      uses: azure/login@v1.4.3
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
    # Run commads to start the azure resources
    - name: start_azure_vm
      run: |
        rgstr=$(az vm list --query "[?tags.${{ env.VM_TAG_KEY }} == '${{ env.VM_TAG_VLAUE }}'].{Group:resourceGroup}" -o tsv)
        for vmrg in ${rgstr[@]}; do
          echo "running command with $vmrg"
          vmstr=$(az vm list -g $vmrg --query "[?tags.${{ env.VM_TAG_KEY }} == '${{ env.VM_TAG_VLAUE }}'].{Name:name}" -o tsv)
          for vm in ${vmstr[@]}; do
            echo "Starting Azure VM $vm"
            az vm start -g $vmrg -n $vm
          done  
        done
        
    - name: start_azure_aks_cluster
      run: |
        krgstr=$(az aks list --query "[?tags.${{ env.AKS_TAG_KEY }} == '${{ env.AKS_TAG_VLAUE }}'].{Group:resourceGroup}" -o tsv)
        for krg in ${krgstr[@]}; do
          echo "running command with $krg"
          kclusterstr=$(az aks list -g $krg --query "[?tags.${{ env.VM_TAG_KEY }} == '${{ env.VM_TAG_VLAUE }}'].{Name:name}" -o tsv)
          for kcluster in ${kclusterstr[@]}; do
            echo "Starting Azure VM $kcluster"
            az vm start -g $krg -n $kcluster
          done  
        done